# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c74a81a39d2f29f85f93f10d42d2475ec84a0410ee53146a463492d7e83bb6f72a5f264256e2d46b7eb8de9848fe380db5ce6749c37ef137bf5868e2cc9f08bb

test:
  secret_key_base: d32b09f1488f5ca0c7c5991e850caebbbaf3e08c7387091550179e61ff02b3fd99faafdf4730877b22a05699e1e64fb0849a29274ec88f4b6ba91c4c51983aaf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
